# Generated by Django 4.1 on 2022-09-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('grandtotal', models.IntegerField()),
                ('customername', models.CharField(max_length=50)),
                ('customeremail', models.CharField(max_length=50)),
                ('customeraddress', models.CharField(max_length=50)),
                ('customerphone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pimage', models.CharField(max_length=40)),
                ('pdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('unitprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('dtotal', models.IntegerField()),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermodel')),
            ],
        ),
    ]
