# Generated by Django 4.1 on 2022-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pprice', models.IntegerField(max_length=20)),
                ('pdescription', models.TextField(max_length=255)),
                ('pimage', models.CharField(max_length=20)),
                ('pstock', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
