# Generated by Django 4.1 on 2022-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pstock',
            field=models.IntegerField(),
        ),
    ]
