# Generated by Django 4.1 on 2022-09-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_pprice_alter_product_pstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('grandtotal', models.IntegerField()),
                ('customername', models.CharField(max_length=50)),
                ('customeremail', models.CharField(max_length=50)),
                ('customeraddress', models.CharField(max_length=50)),
                ('customerphone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pimage', models.CharField(max_length=40)),
                ('pdescription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
