# Generated by Django 4.1 on 2022-09-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ordermoder_productmodel_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModer',
            new_name='OrderModel',
        ),
    ]
