# Generated by Django 4.1 on 2022-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_detailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pimage', models.CharField(max_length=40)),
                ('pdescription', models.TextField()),
            ],
        ),
    ]
