# Generated by Django 4.1 on 2022-09-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_productcardmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCardModel',
        ),
    ]
